### ISSUE TITLE
Add dependabot[bot] <support@github.com>

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/projects-bots-api#1]
We plan on leveraging this API for validating the ECA status of bots. 

We would need to include an entry for dependabot[bot] <support@github.com> to support the following use case: https://bugs.eclipse.org/bugs/show_bug.cgi?id=552628

**Comment by mbarbero** [comment]
Done.

```
$ curl -sSL "https://api.eclipse.org/bots?q=dependabot" | jq
  {
    "id": 185,
    "projectId": "tools.cdt",
    "username": "genie.cdt",
    "email": "cdt-bot@eclipse.org",
    "github.com": {
      "username": "eclipse-cdt-bot",
      "email": "cdt-bot@eclipse.org"
    },
    "github.com-dependabot": {
      "username": "dependabot[bot]",
      "email": "support@github.com"
    }
  }
]
```

Note that dependabot, while having the same username and same email, is attached as a specific bot account to the project using it. So you'll have to check that the repository for which the request is being made is the one with "projectId".

**Comment by joakime** [comment]
Does this mean each project needs to request that dependabot be added to that specific project?

**Comment by mbarbero** [comment]
> Does this mean each project needs to request that dependabot be added to that specific project?

For now, yes. If it deems to be something that most projects want, we may think of adding it everywhere.

**Comment by olamy** [comment]
> > Does this mean each project needs to request that dependabot be added to that specific project?
> 
> For now, yes. If it deems to be something that most projects want, we may think of adding it everywhere.

@mbarbero what is the procedure for that? I need to ask this for Jetty

**Comment by mbarbero** [comment]
Just open a ticket with your request at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=GitHub
