### ISSUE TITLE
Allow Step Security bot PRs to avoid ECA check

### ISSUE THREAD

**Issue by tellison** [EclipseFdn/projects-bots-api#14]
The Adoptium projects would like to use the [Step Security Secure Workflows](https://github.com/step-security/secure-workflows) tool to harden the work flows of our repositories.

The tool opens PRs with recommended changes that will be reviewed by committers. In order to merge the PR the ECA check [will need to permit](https://github.com/adoptium/adoptium/issues/187#issuecomment-1302111960) the [tool bot](https://github.com/step-security-bot) as an author. This is deemed acceptable as the tool authors do not claim any copyright over the resulting changes.

The bot is "Step Security Bot (bot@stepsecurity.io)"

**Comment by mbarbero** [comment]
👍

**Comment by netomi** [comment]
The step security bot has been added to the whitelist of the eca check app for some time now: https://gitlab.eclipse.org/eclipsefdn/it/api/git-eca-rest-api/-/blob/main/src/main/resources/application.properties#L53

I think we can close this issue.

**Comment by autumnfound** [comment]
Closing issue as this should now be supported in the Git ECA application directly!
