### ISSUE TITLE
Bot endpoint no longer matches previous output

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/projects-bots-api#3]
When calling the bot endpoint, resources now return with different names for the many bot account subtypes (i.e. github, ossrh, dockerhub). Where before these were the URLs that the bots were active on, it is now just the hostname for the given endpoint in camelcase.

```
{
    "dockerHub":{
        "username":"codewindbot",
        "email":"codewind-bot@eclipse.org"
    },
    "email":"codewind-bot@eclipse.org",
    "gitHub":{
        "username":"eclipse-codewind-bot",
        "email":"codewind-bot@eclipse.org"
    },
    "id":3,
    "projectId":"ecd.codewind",
    "username":"genie.codewind"
}
```

**Comment by mbarbero** [comment]
Regression introduced in 4e27764
