### ISSUE TITLE
eclipse-corev-bot is missing from API

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/projects-bots-api#8]
I took a look at the logs for https://github.com/orgs/openhwgroup and saq that eclipse-corev-bot was removed. 

 eclipse-corev-bot is missing from https://api.eclipse.org/bots/

**Comment by chrisguindon** [comment]
I manually added the bot for now.

**Comment by mbarbero** [comment]
@fredg02 could you please take this one?

**Comment by fredg02** [comment]
Done.
